@misc{ref01,
  note = {刘瑞. 基于深度强化学习的虚拟角色运动控制研究[D]. 北京邮电大学, 2025. DOI:10.26969/d.cnki.gbydu.2025.001175.}
}

@misc{ref02,
  note = {吴亚雄. 肌肉骨骼机器人抗干扰性分析与运动控制研究[D]. 北京科技大学, 2024. DOI:10.26945/d.cnki.gbjku.2024.000017.}
}

@misc{ref03,
  note = {陈文谦. 基于强化学习的下肢肌肉骨骼模型非节律运动控制方法研究[D]. 大连理工大学, 2024. DOI:10.26991/d.cnki.gdllu.2024.003142.}
}

@misc{ref04,
  note = {董凯月. 基于肌肉骨骼模型的虚拟人多样性运动生成技术[D]. 东南大学, 2023. DOI:10.27014/d.cnki.gdnau.2023.004503.}
}

@misc{ref05,
  note = {陶然. 基于肌肉骨骼模型的虚拟人运动生成与控制[D]. 东南大学, 2022. DOI:10.27014/d.cnki.gdnau.2022.001909.}
}

@misc{ref06,
  note = {原建博.仿人肌肉驱动式机械臂的设计、建模与运动控制研究[D].北京科技大学,2024.DOI:10.26945/d.cnki.gbjku.2024.000299.}
}

@misc{ref07,
  note = {蔡闯. 面向膝关节外骨骼机器人的人体步态识别及预测控制[D]. 昆明理工大学, 2024. DOI:10.27200/d.cnki.gkmlu.2024.000416.}
}

@misc{ref08,
  note = {李嘉聪. 基于数据驱动的上肢康复机器人交互控制与实验研究[D]. 长春工业大学, 2023. DOI:10.27805/d.cnki.gccgy.2023.000956.}
}

@misc{ref09,
  note = {朱易凡,刘晋飞,黄华,等. 基于模仿学习的工业机器人控制策略研究[J/OL].控制与决策,1-12[2026-01-16].https://doi.org/10.13195/j.kzyjc.2025.0749.}
}

@misc{ref10,
  note = {王瑞,董枫,向明,等. 基于深度强化学习算法的机械臂点位运动控制研究[J].机械管理开发,2025,40(12):286-290.DOI:10.16525/j.cnki.cn14-1134/th.2025.12.095.}
}

@misc{ref11,
  note = {羊清宇,袁亮,吕凯. 基于机械臂模仿学习的高效轨迹优化策略[J/OL].电子测量技术,1-11[2026-01-16].https://link.cnki.net/urlid/11.2175.tn.20251202.1819.010.}
}

@misc{ref12,
  note = {张金柱. 智能机器人机械臂运动控制算法优化[J].陶瓷,2025,(09):9-10.DOI:10.19397/j.cnki.ceramics.2025.09.001.}
}

@misc{ref13,
  note = {刘权增.四足机器人路径规划与运动控制算法研究[D].安徽理工大学,2025.DOI:10.26918/d.cnki.ghngc.2025.001665.}
}

@misc{ref14,
  note = {张峰,曹乐,徐浩洋,等. 基于中枢模式发生器的机器人足端轨迹规划[J].中国医学物理学杂志,2024,41(01):72-80.}
}

@misc{ref15,
  note = {刘小宇,姚舒琪.运动想象脑机接口对运动员神经肌肉控制能力的增强机制研究[C]//中国体育科学学会.第十四届全国体育科学大会学术成果汇编——论文专题报告(运动心理学分会).陕西师范大学;,2025:407-409.DOI:10.26914/c.cnkihy.2025.085204.}
}

@misc{ref16,
  note = {陈晋音,瞿康赟,郑海斌. 基于模仿学习的深度强化学习训练数据推断攻击[J].网络与信息安全学报,2025,11(05):50-67.}
}

@misc{ref17,
  note = {王海斌,程军. 短跑训练中神经肌肉控制能力的评估与干预策略[J].当代体育科技,2025,15(24):19-22.DOI:10.16655/j.cnki.2095-2813.2025.24.007.}
}

@misc{ref18,
  note = {郑佳伟,徐兵,魏子轩,等. 髋部肌群强化对慢性踝关节不稳患者下肢生物力学特征及神经肌肉控制的影响[J/OL].医用生物力学,1-14[2026-01-16].https://link.cnki.net/urlid/31.1624.R.20250715.1437.002.}
}

@misc{ref19,
  note = {Joos E, Péan F, Goksel O. Reinforcement learning of musculoskeletal control from functional simulations[C]//International Conference on Medical Image Computing and Computer-Assisted Intervention. Cham: Springer International Publishing, 2020: 135-145.}
}

@misc{ref20,
  note = {Simos M, Chiappa A S, Mathis A. Reinforcement learning-based motion imitation for physiologically plausible musculoskeletal motor control[J]. arXiv preprint arXiv:2503.14637, 2025.}
}

@misc{ref21,
  note = {Loi I, Zacharaki E I, Moustakas K. Machine learning approaches for 3d motion synthesis and musculoskeletal dynamics estimation: a survey[J]. IEEE transactions on visualization and computer graphics, 2023, 30(8): 5810-5829.}
}

@misc{ref22,
  note = {Zhou Y ,Reddy C ,Yin W , et al. An Improved Head--Neck Musculoskeletal Model Incorporating Cervical Spine Rhythms Measured by Dynamic Radiography In Vivo[J].Annals of Biomedical Engineering,2026,(prepublish):1-10.DOI:10.1007/S10439-026-03971-8.}
}

@misc{ref23,
  note = {Zhou Z ,Ai Q ,Li M , et al. The Design and Adaptive Control of a Parallel Chambered Pneumatic Muscle-Driven Soft Hand Robot for Grasping Rehabilitation[J].Biomimetics,2024,9(11):706-706.DOI:10.3390/BIOMIMETICS9110706.}
}

@misc{ref24,
  note = {Yongdeok K ,Yiyuan Y ,Xiaotian Z , et al. Remote control of muscle-driven miniature robots with battery-free wireless optoelectronics.[J].Science robotics,2023,8(74):eadd1053-eadd1053.DOI:10.1126/SCIROBOTICS.ADD1053.}
}

@misc{ref25,
  note = {Mahdi H . Dynamics and Computed-Muscle-Force Control of a Planar Muscle-Driven Snake Robot[J].Actuators,2022,11(7):194-194.DOI:10.3390/ACT11070194.}
}

@misc{ref26,
  note = {张天明.人体运动生物力学建模及仿真研究[D].吉林大学,2024.DOI:10.27162/d.cnki.gjlin.2024.000781.}
}

@misc{ref27,
  note = {苗展豪.基于人体上肢骨骼肌肉力学特性的仿生前臂机构设计与运动分析[D].吉林农业大学,2023.DOI:10.27163/d.cnki.gjlnu.2023.000805.}
}

@misc{ref28,
  note = {孙立博,文吉伟,田瑞,等.基于视频数据的肌肉骨骼虚拟人运动控制[J/OL].系统仿真学报,1-17[2026-05-22].https://link.cnki.net/urlid/11.3092.v.20260408.1318.008.}
}

@misc{ref29,
  note = {张煜.基于人体下肢骨骼肌肉力学特性的仿生腿足机构结构设计与仿真分析[D].吉林农业大学,2023.DOI:10.27163/d.cnki.gjlnu.2023.000128.}
}

@misc{ref30,
  note = {胡锦涛.基于深度强化学习和模仿学习的机械臂轨迹跟踪控制研究[D].东莞理工学院,2025.DOI:10.44357/d.cnki.gdgut.2025.000090.}
}
