# TeXstudio / TeX Live 2023 兼容编译配置
# 推荐命令：XeLaTeX 编译 2 次；如使用 latexmk，请执行：latexmk -pdf hutbthesis_main.tex
$pdf_mode = 1;
$pdflatex = 'xelatex -synctex=1 -interaction=nonstopmode -halt-on-error %O %S';
$max_repeat = 5;
