
name: latex Windows CI/CD

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  windows-dev:
    name: Windows CI/CD
    timeout-minutes: 1440
    runs-on: self-hosted:windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: build
        run: |
          call build_latex_tactile.bat
        shell: cmd