from pathlib import Path


def main() -> None:
    output_path = Path(__file__).with_name("manual_test_output.txt")
    lines = [
        "HUTB manual test output",
        "This file is generated by samples/write_txt_demo.py",
        "If you can see this file, Python debug launch is working.",
    ]
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated: {output_path}")


if __name__ == "__main__":
    main()
