# config/__init__.py
# 全局配置模块统一入口 —— 仅导出公共固定参数

from .carla_config import (
    CARLA_HOST, CARLA_PORT, CARLA_TIMEOUT,
    SYNC_MODE, SIMULATION_FPS, FIXED_DELTA_SECONDS,
    EGO_VEHICLE_BLUEPRINT, ADV_VEHICLE_BLUEPRINT,
    DEFAULT_SPAWN_INDEX,
    COLLISION_THRESHOLD, MIN_SAFE_DISTANCE, VEHICLE_MAX_SPEED,
    RGB_CAMERA_CONFIG, LIDAR_CONFIG, SENSOR_UPDATE_FPS,
    MAX_EPISODE_STEPS, EPISODE_TIMEOUT,
    COLLISION_PENALTY, SUCCESS_REWARD,
    RESULTS_DIR, MODELS_DIR, LOGS_DIR,
    SCENARIOS_OUTPUT_DIR, EVALUATION_OUTPUT_DIR,
    COMPARISON_OUTPUT_DIR, PLOTS_OUTPUT_DIR,
)

from .dqn_config import (
    STATE_SIZE as DQN_STATE_SIZE,
    ACTION_SIZE as DQN_ACTION_SIZE,
    HIDDEN_SIZES as DQN_HIDDEN_SIZES,
    ATTENTION_HEAD_DIM, NUM_ATTENTION_HEADS, ATTENTION_DROPOUT,
    LEARNING_RATE as DQN_LR, GAMMA as DQN_GAMMA,
    TAU as DQN_TAU, TARGET_UPDATE_FREQ,
    MEMORY_SIZE, BATCH_SIZE as DQN_BATCH_SIZE, MIN_REPLAY_SIZE,
    EPSILON_START, EPSILON_MIN, EPSILON_DECAY,
    TRAIN_EVERY_N_STEPS as DQN_TRAIN_EVERY,
    MAX_EPISODES as DQN_MAX_EPISODES,
    SAVE_EVERY_N_EPISODES as DQN_SAVE_EVERY,
    LOG_EVERY_N_EPISODES as DQN_LOG_EVERY,
)

from .ppo_config import (
    STATE_SIZE as PPO_STATE_SIZE,
    ACTION_SIZE as PPO_ACTION_SIZE, ACTION_STD,
    HIDDEN_SIZES as PPO_HIDDEN_SIZES,
    ACTOR_HIDDEN, CRITIC_HIDDEN, ACTIVATION as PPO_ACTIVATION,
    GAMMA as PPO_GAMMA, LAMBDA as PPO_LAMBDA,
    EPS_CLIP, UPDATE_EVERY as PPO_UPDATE_EVERY,
    UPDATE_POLICY_TIMES, BATCH_SIZE as PPO_BATCH_SIZE,
    LR_ACTOR, LR_CRITIC,
    SMOOTH_ENABLED, SMOOTH_EPS_LOW, SMOOTH_EPS_HIGH, SMOOTH_BETA,
    VALUE_LOSS_COEF, ENTROPY_COEF, MAX_GRAD_NORM,
    MAX_EPISODES as PPO_MAX_EPISODES,
    SAVE_EVERY_N_EPISODES as PPO_SAVE_EVERY,
    LOG_EVERY_N_EPISODES as PPO_LOG_EVERY,
)
