
name: Auto test

on: [push, pull_request]
    
jobs:
  work:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          # github action 默认签出只包含最后一次提交
          # 解决方案参考：https://stackoverflow.com/questions/62334460/git-history-in-a-github-action
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Set up Python
        # 这是设置Python action的版本，不是Python的版本
        uses: actions/setup-python@v5
        with:
          python-version: '3.7' # 指定python版本
          # 可选 - x64 or x86 架构，默认为 x64
          architecture: 'x64'
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests gitpython
      - name: Launch Simulation
        run: python launch.py -t ${{ secrets.GITHUB_TOKEN }} # 执行

      # 触发github action
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: pedestrian/undergraduate
          root_file: hutbthesis_main.tex
          texlive_version: 2023
          latexmk_use_xelatex: true
          # 下载安装Times New Roman字体
          pre_compile: |
            apk add msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f